export const PAYMENT_REQUEST='PAYMENT_REQUEST';
export const PAYMENT_SUCCESS='PAYMENT_SUCCESS';
export const PAYMENT_FAIL='PAYMENT_FAIL';
export const PAYMENT_RESET='PAYMENT_RESET';

export const PAYDETAILS_REQUEST='PAYDETAILS_REQUEST';
export const PAYDETAILS_SUCCESS='PAYDETAILS_SUCCESS';
export const PAYDETAILS_FAIL='PAYDETAILS_FAIL';
